# Copyright 2026 The RLinf Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

import copy
from typing import Any

import numpy as np
import torch

from rlinf.envs.wrappers.collect_episode import CollectEpisode


class CollectRLTActorSegments(CollectEpisode):
    """Export only action chunks that were generated by the Stage2 RLT actor.

    This wrapper is intended to sit outside the regular ``CollectEpisode``
    wrapper. The inner collector continues to receive every environment step,
    while this collector records only chunks explicitly marked by
    :meth:`set_next_actor_chunk_flags`.

    The flag comes from ``forward_inputs["actor_switch"]`` in the rollout
    result, so it describes the policy that generated the action chunk. This is
    more precise than reading ``rlt_switch_flags`` from the post-step info: the
    latter may change after the user presses the switch pedal midway through an
    already-generated reference chunk.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.num_envs != 1:
            raise ValueError(
                "CollectRLTActorSegments currently supports the real-world "
                f"single-env path only, got num_envs={self.num_envs}."
            )
        self._next_actor_chunk_flags: np.ndarray | None = None
        self._actor_recording = [False] * self.num_envs
        self._last_observations: list[Any | None] = [None] * self.num_envs

    def set_next_actor_chunk_flags(self, flags: Any) -> None:
        """Set action provenance for the next ``chunk_step`` call.

        Args:
            flags: Per-env boolean tensor/array. Extra dimensions are reduced
                with ``all`` because a routed real-world action chunk has one
                policy source for every sub-step.
        """
        array = self._to_numpy(flags)
        if array is None:
            raise ValueError("Actor chunk flags cannot be None.")
        array = np.asarray(array, dtype=bool)
        if array.ndim == 0:
            array = np.full((self.num_envs,), bool(array), dtype=bool)
        else:
            if array.shape[0] != self.num_envs:
                raise ValueError(
                    "Actor chunk flags must have the environment batch as their "
                    f"leading dimension; got shape={array.shape}, num_envs={self.num_envs}."
                )
            array = array.reshape(self.num_envs, -1).all(axis=1)
        self._next_actor_chunk_flags = array

    def reset(self, *, seed=None, options=None):
        obs, info = super().reset(seed=seed, options=options)
        self._buffers = [self._new_buffer() for _ in range(self.num_envs)]
        self._actor_recording = [False] * self.num_envs
        self._next_actor_chunk_flags = None
        self._last_observations = [
            self._slice_copy(obs, env_idx) for env_idx in range(self.num_envs)
        ]
        return obs, info

    def chunk_step(self, chunk_actions):
        actor_flags = self._consume_actor_chunk_flags()
        obs_list, rewards, terminations, truncations, infos_list = self.env.chunk_step(
            chunk_actions
        )

        chunk_size = len(obs_list) if isinstance(obs_list, (list, tuple)) else 1
        for step_idx in range(chunk_size):
            step_action = (
                chunk_actions[:, step_idx]
                if isinstance(chunk_actions, (torch.Tensor, np.ndarray))
                and chunk_actions.ndim > 1
                else chunk_actions
            )
            step_obs = (
                obs_list[step_idx] if isinstance(obs_list, (list, tuple)) else obs_list
            )
            step_reward = (
                rewards[:, step_idx] if getattr(rewards, "ndim", 1) > 1 else rewards
            )
            step_term = (
                terminations[:, step_idx]
                if getattr(terminations, "ndim", 1) > 1
                else terminations
            )
            step_trunc = (
                truncations[:, step_idx]
                if getattr(truncations, "ndim", 1) > 1
                else truncations
            )
            step_info = (
                copy.deepcopy(infos_list[step_idx])
                if isinstance(infos_list, (list, tuple))
                else copy.deepcopy(infos_list)
            )
            self._record_actor_step(
                actor_active=bool(actor_flags[0]),
                action=step_action,
                obs=step_obs,
                reward=step_reward,
                terminated=step_term,
                truncated=step_trunc,
                info=step_info,
            )

        return obs_list, rewards, terminations, truncations, infos_list

    def _consume_actor_chunk_flags(self) -> np.ndarray:
        flags = self._next_actor_chunk_flags
        self._next_actor_chunk_flags = None
        if flags is None:
            raise RuntimeError(
                "Missing actor provenance for RLT actor-segment collection. "
                "EnvWorker must call set_next_actor_chunk_flags() before chunk_step()."
            )
        return flags

    def _start_actor_segment(self, env_idx: int) -> None:
        self._buffers[env_idx] = self._new_buffer()
        self._episode_success[env_idx] = False
        self._segment_ids[env_idx] = 0
        self._pending_obs[env_idx] = None
        self._pending_info[env_idx] = None
        previous_obs = self._last_observations[env_idx]
        if previous_obs is not None:
            self._seed_reset_frame(env_idx, copy.deepcopy(previous_obs))
        self._actor_recording[env_idx] = True

    def _record_actor_step(
        self,
        *,
        actor_active: bool,
        action,
        obs,
        reward,
        terminated,
        truncated,
        info,
    ) -> None:
        env_idx = 0
        done = self._scalar_flag(terminated, env_idx) or self._scalar_flag(
            truncated, env_idx
        )

        if actor_active:
            if not self._actor_recording[env_idx]:
                self._start_actor_segment(env_idx)
            self._record_step(action, obs, reward, terminated, truncated, info)
            if done:
                self._maybe_flush(terminated, truncated)
                if self._buffers[env_idx]["actions"]:
                    # ``CollectEpisode`` deliberately keeps a failed
                    # termination buffered when only_success=True. A sidecar
                    # actor fragment must discard it before the next rollout.
                    self._reset_env_buffer(env_idx)
                self._actor_recording[env_idx] = False
        elif done:
            # The episode ended before control reached the actor. Advance the
            # collector episode state without emitting an empty dataset item.
            self._reset_env_buffer(env_idx)
            self._actor_recording[env_idx] = False

        self._last_observations[env_idx] = self._slice_copy(obs, env_idx)
